// angular-frontend/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpClient }                   from '@angular/common/http';
import { CommonModule }                 from '@angular/common';
import { FormsModule }                  from '@angular/forms';
import { Subject }                      from 'rxjs';
import {
  debounceTime,
  distinctUntilChanged,
  takeUntil,
  finalize
} from 'rxjs/operators';

/* ── Interfaces ─────────────────────────────────────────────── */
export interface Story {
  id:     number;
  title:  string;
  url:    string | null;
  score?: number;
  by?:    string;
  time?:  number;
}

export interface ApiResponse {
  data:  Story[];
  total: number;
}

/* ── Component ──────────────────────────────────────────────── */
@Component({
  selector:    'app-root',
  standalone:  true,
  imports:     [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrls:   ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {

  /* ── State ─────────────────────────────────────────────── */
  stories:  Story[]       = [];
  total     = 0;
  page      = 1;
  pageSize  = 10;
  search    = '';
  sort      = 'latest';
  loading   = false;
  error:    string | null = null;

  /* ── RxJS ──────────────────────────────────────────────── */
  private searchSubject = new Subject<string>();
  private destroy$      = new Subject<void>();

  /* Skeleton placeholder array (10 empty slots) */
  readonly skeletonItems = Array(10).fill(null);

  /* ── API endpoint — change to your backend URL ─────────── */
  private readonly API = 'http://localhost:5000/api/stories';

  constructor(private http: HttpClient) {}

  /* ── Lifecycle ─────────────────────────────────────────── */
  ngOnInit(): void {
    // Initial load
    this.loadStories();

    // Debounced search
    this.searchSubject.pipe(
      debounceTime(350),
      distinctUntilChanged(),
      takeUntil(this.destroy$)
    ).subscribe(() => {
      this.page = 1;
      this.loadStories();
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  /* ── Data Fetching ─────────────────────────────────────── */
  loadStories(): void {
    this.loading = true;
    this.error   = null;

    const params = `page=${this.page}&search=${encodeURIComponent(this.search)}&sort=${this.sort}`;

    this.http
      .get<ApiResponse>(`${this.API}?${params}`)
      .pipe(
        finalize(() => (this.loading = false)),
        takeUntil(this.destroy$)
      )
      .subscribe({
        next: (res) => {
          this.stories = res.data  ?? [];
          this.total   = res.total ?? 0;
        },
        error: (err) => {
          this.error   = err?.error?.message ?? err?.message ?? 'Failed to fetch stories.';
          this.stories = [];
        }
      });
  }

  /** Fired on every keypress in the search input */
  onSearchInput(): void {
    this.searchSubject.next(this.search);
  }

  /** Clear button handler */
  clearSearch(): void {
    this.search = '';
    this.page   = 1;
    this.loadStories();
  }

  /** Sort change handler */
  onSortChange(newSort: string): void {
    this.sort = newSort;
    this.page = 1;
    this.loadStories();
  }

  /* ── Pagination ────────────────────────────────────────── */
  get totalPages(): number  { return Math.ceil(this.total / this.pageSize) || 1; }
  get pageStart():  number  { return (this.page - 1) * this.pageSize + 1; }
  get pageEnd():    number  { return Math.min(this.page * this.pageSize, this.total); }
  get isFirstPage(): boolean { return this.page <= 1; }
  get isLastPage():  boolean { return this.page >= this.totalPages; }

  prevPage(): void {
    if (!this.isFirstPage) { this.page--; this.loadStories(); }
  }

  nextPage(): void {
    if (!this.isLastPage) { this.page++; this.loadStories(); }
  }

  goToPage(p: number): void {
    if (p >= 1 && p <= this.totalPages && p !== this.page) {
      this.page = p;
      this.loadStories();
    }
  }

  /* ── Utilities ─────────────────────────────────────────── */

  /** Extracts clean hostname from URL for the read button label */
  getHostname(url: string | null): string {
    if (!url) return '';
    try   { return new URL(url).hostname.replace(/^www\./, ''); }
    catch { return ''; }
  }

  /** Returns page numbers around current page (window of ±2) */
  getPageNumbers(): number[] {
    const delta = 2;
    const from  = Math.max(1, this.page - delta);
    const to    = Math.min(this.totalPages, this.page + delta);
    const pages: number[] = [];
    for (let i = from; i <= to; i++) pages.push(i);
    return pages;
  }

  /** trackBy function for *ngFor performance */
  trackByStory(_index: number, story: Story): number {
    return story.id;
  }
}
<div class="hn-root">

  <!-- ══ HEADER ══════════════════════════════════════════════ -->
  <header class="hn-header" role="banner">

    <div class="hn-header-left">

      <!-- Logo badge -->
      <div class="hn-badge" aria-label="Hacker News">
        <span class="badge-text">HN</span>
      </div>

      <!-- Brand -->
      <div class="hn-brand">
        <span class="hn-brand-name">Hacker News</span>
        <span class="hn-brand-tag">Live Feed</span>
      </div>

      <!-- Separator -->
      <div class="hn-divider" aria-hidden="true"></div>

      <!-- Live pill -->
      <div class="hn-status-pill">
        <span class="hn-live-dot" aria-hidden="true"></span>
        <span>Newest</span>
      </div>

    </div>

    <div class="hn-header-right">

      <!-- Story count chip -->
      <div class="hn-count-chip"
           *ngIf="!loading && total > 0"
           aria-live="polite">
        <span class="chip-label">Stories</span>
        <span class="chip-value">{{ total | number }}</span>
      </div>

      <!-- ✅ FIXED: Search with proper SVG icon sizing -->
      <div class="hn-search-wrap">

        <!-- Search icon: strictly 16×16, no overflow -->
        <span class="hn-search-icon" aria-hidden="true">
          <svg viewBox="0 0 20 20" fill="none"
               xmlns="http://www.w3.org/2000/svg"
               width="16" height="16"
               style="display:block;width:16px;height:16px;flex-shrink:0;">
            <circle cx="9" cy="9" r="5.5"
                    stroke="currentColor" stroke-width="1.6"/>
            <path d="M13.5 13.5L17 17"
                  stroke="currentColor" stroke-width="1.6"
                  stroke-linecap="round"/>
          </svg>
        </span>

        <input
          class="hn-search"
          type="text"
          placeholder="Search stories…"
          [(ngModel)]="search"
          (input)="onSearchInput()"
          aria-label="Search Hacker News stories"
          autocomplete="off"
          spellcheck="false"
        />

        <button
          *ngIf="search"
          class="hn-search-clear"
          (click)="clearSearch()"
          aria-label="Clear search"
          type="button"
        >
          <svg viewBox="0 0 14 14" fill="none"
               xmlns="http://www.w3.org/2000/svg"
               width="10" height="10"
               style="display:block;width:10px;height:10px;">
            <path d="M1 1l12 12M13 1L1 13"
                  stroke="currentColor" stroke-width="2"
                  stroke-linecap="round"/>
          </svg>
        </button>

      </div>

      <!-- Sort Dropdown -->
      <div class="hn-sort-wrap">
        <label for="sort-select" class="hn-sort-label">Sort:</label>
        <select
          id="sort-select"
          class="hn-sort-select"
          [(ngModel)]="sort"
          (change)="onSortChange(sort)"
          aria-label="Sort stories">
          <option value="latest">Latest</option>
          <option value="oldest">Oldest</option>
        </select>
      </div>

    </div>
  </header>


  <!-- ══ MAIN ════════════════════════════════════════════════ -->
  <main class="hn-layout" role="main">

    <!-- Toolbar row -->
    <div class="hn-toolbar">
      <div class="hn-toolbar-left">

        <h1 class="hn-toolbar-title">
          <ng-container *ngIf="search; else defaultTitle">
            Results for &ldquo;<em>{{ search }}</em>&rdquo;
          </ng-container>
          <ng-template #defaultTitle>Latest Stories</ng-template>
        </h1>

        <p class="hn-toolbar-sub">
          <ng-container *ngIf="loading">
            Fetching from API&hellip;
          </ng-container>
          <ng-container *ngIf="!loading && total > 0">
            Showing&nbsp;
            <span class="hi">{{ pageStart }}–{{ pageEnd }}</span>
            &nbsp;of&nbsp;
            <span class="hi">{{ total | number }}</span>
            &nbsp;stories
          </ng-container>
          <ng-container *ngIf="!loading && total === 0 && !error">
            Hacker News · Technology &amp; Startup Feed
          </ng-container>
        </p>

      </div>

      <!-- Page badge -->
      <div class="hn-page-badge"
           *ngIf="!loading && totalPages > 1"
           [attr.aria-label]="'Page ' + page + ' of ' + totalPages">
        <span class="pg-current">{{ page }}</span>
        <span class="pg-sep">/</span>
        <span class="pg-total">{{ totalPages }}</span>
      </div>
    </div>


    <!-- ── ERROR ───────────────────────────────────────────── -->
    <div class="hn-error" *ngIf="error && !loading" role="alert">
      <span class="error-icon">
        <svg viewBox="0 0 20 20" fill="none" width="16" height="16"
             style="display:block;width:16px;height:16px;">
          <circle cx="10" cy="10" r="8" stroke="currentColor" stroke-width="1.5"/>
          <path d="M10 6v4.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
          <circle cx="10" cy="14" r=".9" fill="currentColor"/>
        </svg>
      </span>
      <span class="error-msg">{{ error }}</span>
      <button class="error-retry" (click)="loadStories()" type="button">Retry</button>
    </div>


    <!-- ── SKELETON LOADER ────────────────────────────────── -->
    <ul class="hn-skeleton-list"
        *ngIf="loading"
        aria-label="Loading stories"
        aria-busy="true">
      <li class="hn-sk-item"
          *ngFor="let _ of skeletonItems; let i = index"
          [style.animation-delay]="(i * 55) + 'ms'">
        <div class="sk-num"></div>
        <div class="sk-body">
          <div class="sk-line sk-title" [style.width.%]="55 + (i % 5) * 8"></div>
          <div class="sk-line sk-sub"   [style.width.%]="20 + (i % 4) * 6"></div>
        </div>
      </li>
    </ul>


    <!-- ── STORY LIST ─────────────────────────────────────── -->
    <ul class="hn-list"
        *ngIf="!loading && stories.length > 0"
        aria-label="Hacker News stories">

      <li class="hn-item"
          *ngFor="let story of stories; let i = index; trackBy: trackByStory"
          [style.animation-delay]="(i * 45) + 'ms'">

        <!-- Index number -->
        <div class="hn-item-index" aria-hidden="true">{{ pageStart + i }}</div>

        <!-- Body -->
        <div class="hn-item-body">

          <!-- Title -->
          <a *ngIf="story.url; else plainTitle"
             [href]="story.url"
             target="_blank"
             rel="noreferrer noopener"
             class="hn-item-title"
             [title]="story.title">{{ story.title }}</a>

          <ng-template #plainTitle>
            <span class="hn-item-title hn-item-title--plain">{{ story.title }}</span>
          </ng-template>

          <!-- Meta row -->
          <div class="hn-item-meta">

            <!-- Read button -->
            <a *ngIf="story.url; else noLink"
               [href]="story.url"
               target="_blank"
               rel="noreferrer noopener"
               class="hn-read-btn"
               [attr.aria-label]="'Read: ' + story.title">
              <svg viewBox="0 0 12 12" fill="none" width="10" height="10"
                   style="display:block;width:10px;height:10px;flex-shrink:0;">
                <path d="M2 10L10 2M10 2H4M10 2v6"
                      stroke="currentColor" stroke-width="1.6"
                      stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              {{ getHostname(story.url) || 'Read Article' }}
            </a>

            <ng-template #noLink>
              <span class="hn-no-link">— No source</span>
            </ng-template>

            <!-- Story ID -->
            <span class="hn-item-id" [attr.aria-label]="'ID ' + story.id">#{{ story.id }}</span>

          </div>
        </div>
      </li>

    </ul>


    <!-- ── EMPTY STATE ────────────────────────────────────── -->
    <div class="hn-empty"
         *ngIf="!loading && stories.length === 0 && !error"
         role="status">
      <div class="empty-icon-wrap" aria-hidden="true">
        <svg viewBox="0 0 48 48" fill="none" width="32" height="32"
             style="display:block;width:32px;height:32px;">
          <circle cx="22" cy="22" r="14" stroke="currentColor" stroke-width="2"/>
          <path d="M32 32l8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          <path d="M17 22h10" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
        </svg>
      </div>
      <p class="empty-title">No Results Found</p>
      <p class="empty-sub">
        <ng-container *ngIf="search">
          No stories matched &ldquo;{{ search }}&rdquo;.<br>Try a different keyword.
        </ng-container>
        <ng-container *ngIf="!search">
          No stories available right now. Try refreshing.
        </ng-container>
      </p>
    </div>


    <!-- ── PAGINATION ─────────────────────────────────────── -->
    <nav class="hn-pagination"
         *ngIf="!loading && stories.length > 0"
         aria-label="Story pagination">

      <!-- Prev -->
      <button class="hn-page-btn"
              [disabled]="isFirstPage"
              (click)="prevPage()"
              aria-label="Previous page"
              type="button">
        &larr; Prev
      </button>

      <!-- Page numbers -->
      <div class="hn-page-info" aria-live="polite">
        <span class="hn-page-nums">{{ page }} / {{ totalPages }}</span>
        <span class="hn-page-label">Page</span>
      </div>

      <!-- Next -->
      <button class="hn-page-btn"
              [disabled]="isLastPage"
              (click)="nextPage()"
              aria-label="Next page"
              type="button">
        Next &rarr;
      </button>

    </nav>

  </main>


  <!-- ══ FOOTER ══════════════════════════════════════════════ -->
  <footer class="hn-footer" role="contentinfo">
    <p class="footer-line">Powered by Hacker News Official API</p>
    <p class="footer-api">news.ycombinator.com · real-time feed</p>
  </footer>

</div>

// react-frontend/src/App.jsx
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchStories, setPage, setSort } from "./features/storiesSlice";
import "./index.css";

/* ─── App ──────────────────────────────────────────────────────────────── */

export default function App() {
  const dispatch = useDispatch();
  const { items, total, page, sort, loading, error } = useSelector(
    (state) => state.stories
  );
  const [search, setSearch] = useState("");

  useEffect(() => {
    dispatch(fetchStories({ page, search, sort }));
  }, [dispatch, page, search, sort]);

  const totalPages = Math.ceil(total / 10) || 1;
  const pageStart  = (page - 1) * 10 + 1;

  function handleSearch(e) {
    dispatch(setPage(1));
    setSearch(e.target.value);
  }

  function clearSearch() {
    dispatch(setPage(1));
    setSearch("");
  }

  return (
    <div className="hn-root">

      {/* ══════════════════════════════════════════ Header */}
      <header className="hn-header">

        {/* Logo */}
        <a href="/" className="hn-logo">
          <div className="hn-logo-badge">HN</div>
          <div className="hn-logo-wordmark">
            <span className="hn-logo-title">Hacker News</span>
            <span className="hn-logo-sub">Digest</span>
          </div>
        </a>

        <div className="hn-header-divider" />

        {/* Search */}
        <div className="hn-search-wrap">
          <span className="hn-search-icon">⌕</span>
          <input
            className="hn-search"
            type="text"
            placeholder="Search stories…"
            value={search}
            onChange={handleSearch}
            aria-label="Search stories"
          />
          {search && (
            <button
              className="hn-search-clear"
              onClick={clearSearch}
              aria-label="Clear search"
            >
              ×
            </button>
          )}
        </div>

        {/* Sort Dropdown */}
        <div className="hn-sort-wrap">
          <label htmlFor="sort-select" className="hn-sort-label">
            Sort:
          </label>
          <select
            id="sort-select"
            className="hn-sort-select"
            value={sort}
            onChange={(e) => dispatch(setSort(e.target.value))}
            aria-label="Sort stories"
          >
            <option value="latest">Latest</option>
            <option value="oldest">Oldest</option>
          </select>
        </div>

      </header>

      {/* ══════════════════════════════════════════ Main */}
      <main className="hn-main">

        {/* Toolbar */}
        <div className="hn-toolbar">
          <div className="hn-toolbar-left">
            <span className="hn-toolbar-eyebrow">
              {search ? "Search results" : "Latest"}
            </span>
            <span className="hn-toolbar-label">
              {search ? `"${search}"` : "Newest Stories"}
            </span>
          </div>

          {!loading && total > 0 && (
            <div className="hn-toolbar-count">
              <strong>{total.toLocaleString()}</strong> stories
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="hn-error" role="alert">
            <span className="hn-error-icon">⚠</span>
            <span className="hn-error-text">{error}</span>
          </div>
        )}

        {/* Loading */}
        {loading && (
          <div className="hn-state" aria-live="polite">
            <div className="hn-spinner" role="status" aria-label="Loading" />
            <p className="hn-state-text">Fetching stories…</p>
          </div>
        )}

        {/* Story list */}
        {!loading && items.length > 0 && (
          <ul className="hn-list" aria-label="Stories">
            {items.map((story, i) => (
              <li key={story.id} className="hn-item">

                {/* Index */}
                <div className="hn-item-index" aria-hidden="true">
                  <span className="hn-item-num">{pageStart + i}</span>
                </div>

                {/* Content */}
                <div className="hn-item-body">
                  {story.url ? (
                    <a
                      href={story.url}
                      target="_blank"
                      rel="noreferrer"
                      className="hn-item-title"
                    >
                      {story.title}
                    </a>
                  ) : (
                    <span className="hn-item-title" style={{ cursor: "default" }}>
                      {story.title}
                    </span>
                  )}

                  <div className="hn-item-footer">
                    {story.url ? (
                      <a
                        href={story.url}
                        target="_blank"
                        rel="noreferrer"
                        className="hn-item-link"
                        aria-label={`Read article: ${story.title}`}
                      >
                        <span className="hn-item-link-arrow">↗</span>
                        Read Article
                      </a>
                    ) : (
                      <span className="hn-item-nolink">— No link available</span>
                    )}

                    <span className="hn-item-id" aria-label={`Story ID ${story.id}`}>
                      #{story.id}
                    </span>
                  </div>
                </div>

              </li>
            ))}
          </ul>
        )}

        {/* Empty state */}
        {!loading && items.length === 0 && !error && (
          <div className="hn-empty" role="status">
            <div className="hn-empty-icon">◎</div>
            <p className="hn-empty-title">Nothing found</p>
            <p className="hn-empty-sub">
              {search
                ? `No stories match "${search}"`
                : "No stories available right now"}
            </p>
          </div>
        )}

        {/* Pagination */}
        {!loading && items.length > 0 && (
          <nav className="hn-pagination" aria-label="Pagination">
            <button
              className="hn-page-btn"
              disabled={page === 1}
              onClick={() => dispatch(setPage(page - 1))}
              aria-label="Previous page"
            >
              ← Prev
            </button>

            <div className="hn-page-info" aria-live="polite">
              <span className="hn-page-nums">{page} / {totalPages}</span>
              <span className="hn-page-label">Page</span>
            </div>

            <button
              className="hn-page-btn"
              disabled={page === totalPages}
              onClick={() => dispatch(setPage(page + 1))}
              aria-label="Next page"
            >
              Next →
            </button>
          </nav>
        )}

      </main>
    </div>
  );
}
